version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    platform: linux/amd64
    user: "10001:0"
    restart: on-failure:3
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword!2024"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  redis:
    image: redis:8.0-M04-bookworm
    container_name: redis
    platform: linux/amd64
    restart: on-failure:3
    command: ["redis-server"]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=SuperSecret123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: SuperSecret123
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - backend

volumes:
  sql_data:
  redis_data:

networks:
  backend:
    driver: bridge
