apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-observability
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: default
      tlsSkipVerify: false
      logs:
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
      traces:
        defaultTable: otel_traces
        durationUnit: nanoseconds
        otelEnabled: true
        otelVersion: latest
    secureJsonData:
      password: